### PR TITLE
fix: highlight the correct autocomplete attribute

### LINKED ISSUE #56: Autocomplete audit for invalid attribute highlights the wrong part of the element
When an invalid autocomplete attribute is being highlighted, the first instance of the string is being highlighted instead of the correct one in the autocomplete attribute.

image

### PR DESCRIPTION
**Pull request by socsieng**
image

Fixes #56

### CODE REVIEW

**Comment by samdutton** [comment]
Highlighting doesn't seem to be working for me (running on [form-problems.glitch.me](https://form-problems.glitch.me/)).

Screenshot:

image

**Comment by samdutton** [comment]
Also (probably doesn't relate to this PR, but...) the heading displays **11 common mistakes**, but only three are displayed.

**Comment by socsieng** [comment]
Ran it, it's working for me:

image

The process that I have to follow is:

1. Checkout the branch
2. `npm run build`
3. Update the extension
4. Refresh the page and run the extension

**Comment by socsieng** [comment]
> Also, building and running the extension from this branch, the heading displays 11 common mistakes, but only three are displayed.
>
> (I know this probably doesn't relate to this PR specifically.)

This was related to an issue that was resolved in https://github.com/GoogleChromeLabs/form-troubleshooter/commit/78fb4cd0a4d7de50fa8fc26aa3c682f9f9f5052b

**Comment by samdutton** [comment]
OK — did a hard reset — that fixed it. Not sure what had gone wrong there.

Confirm WAI on [form-problems.glitch.me](https://form-problems.glitch.me).

image

**Pull request merged**
